### ISSUE TITLE
Import of northwind_mysql.sql fails

### ISSUE THREAD

**Issue by antakar** [dalers/mywind#3]
15:45:16	CREATE TABLE `customercustomerdemo` (   `CustomerID` varchar(5) NOT NULL,   `CustomerTypeID` varchar(10) NOT NULL,   PRIMARY KEY (`CustomerID`,`CustomerTypeID`),   KEY `FK_CustomerCustomerDemo` (`CustomerTypeID`),   CONSTRAINT `FK_CustomerCustomerDemo_Customers` FOREIGN KEY (`CustomerID`) REFERENCES `customers` (`CustomerID`),   CONSTRAINT `FK_CustomerCustomerDemo` FOREIGN KEY (`CustomerTypeID`) REFERENCES `customerdemographics` (`CustomerTypeID`) ) ENGINE=InnoDB DEFAULT CHARSET=latin1	Error Code: 1215. Cannot add foreign key constraint	0.047 sec

**Comment by dalers** [comment]
Please report the application and version you were using.

**Comment by eleumik** [comment]
I imported it from Sqlyog (notorious for failing in imports) and worked at first shot, thanks for your work

**Comment by dalers** [comment]
Thanks for your report @eleumik, I hope you find mywind useful.

**Comment by dalers** [comment]
Issue closed based on @eleumik report of successful import.
